server:
  port: 9000

spring:
  application:
    name: mynacos-service-provider

  cloud:
    nacos:
      server-addr: 192.168.23.128:8848

  main:
    allow-bean-definition-overriding: true

  redis:
    host: 192.168.23.128
    port: 6379
    password: chen150928